Ensemble functions
UCSD-E4E/rct_tower_scheduler pull request #7
Opened 2023-05-10 02:00 UTC by Wesleylewis05

created perform_ensemble_functions which executes all ensemble functions in a json file.

2023-05-12 19:54 UTC, hgrehm requested changes
- Instead of looping through all ensembles in `dummy_ensembles.json`, we should just take the current ensemble in `active_ensembles.json`. This file should already have the current ensemble noted, and you can index into the ensemble list at the current ensemble index to know which functions to perform on this call. 
- Please sort imports (abc order)
- Please update the README with the new json file format (now including module name/directory, class, and function)

2023-05-12 20:55 UTC, ntlhui commented
Note that it does not make sense to execute a member function - only static or standalone functions should be executed, as the scheduler should not guarantee existence of any objects while executing a function.

If class context is required, then the entry point function should be responsible for bootstrapping the appropriate object.

2023-05-12 22:56 UTC, ntlhui requested changes

2023-05-12 22:56 UTC, ntlhui commented on ensemble_tests/tester_functions.py
> +    def hello_world():
member function signature should be `def hello_world(self)`

2023-05-12 22:56 UTC, ntlhui commented on ensemble_tests/tester_functions.py
> +    def print_this(string):
member function signature should be `def print_this(self, string: str)`

2023-05-12 22:56 UTC, ntlhui commented on ensemble_tests/tester_functions.py
> +    def add_this(x, y):
member function signature should be `def add_this(self, x, y)`

2023-05-12 22:56 UTC, ntlhui commented on ensemble_tests/tester_functions.py
> +    def subtract_this(x, y):
member function signature should be `def subtract_this(self, x, y)`

2023-05-12 22:56 UTC, ntlhui commented on ensemble_tests/tester_functions.py
> +    def multiply_this(x, y):
member function signature should be `def multiply_this(self, x, y)`

2023-05-12 22:56 UTC, ntlhui commented on dummy_ensembles.json
> +      "function": "print_this",
Consider is this necessarily the appropriate way to define this?

could we potentially define this as `ensemble_tests.tester_functions.SimpleFunctions.print_this`

2023-06-28 21:08 UTC, hgrehm commented on README.md
> +        }
Could we make these examples in the README more generic? For example, the first one might have `"function": "path_to_function.print_function"` to illustrate that we have a path and a function name, separated by a dot.

2023-06-28 21:11 UTC, hgrehm commented on README.md
>  }
Specifications below this block should illustrate the new requirements. For example, `function: path to a callable function followed by function name, separated by a dot` and `inputs: list of arguments to the given function, which the user must confirm are the correct type`

2023-06-28 21:13 UTC, hgrehm commented on scheduler.py
> +            perform_ensemble_functions(0) # TODO Iterate through the ensemble functions
We should be performing the current ensemble specified in `active_ensembles.json`. Specifically, this should be in the `next_ensemble` variable.

2023-06-28 21:20 UTC, hgrehm commented on scheduler.py
>      print("someFunc called!")
Can delete this if it's not being used for testing

2023-07-03 22:09 UTC, merged